"""'Init'

Revision ID: f4e0eb197d3b
Revises: 
Create Date: 2023-05-27 19:31:04.085269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4e0eb197d3b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("birthday", sa.DateTime(), nullable=False),
        sa.Column("additionally", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contacts_additionally"), "contacts", ["additionally"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_birthday"), "contacts", ["birthday"], unique=False
    )
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=True)
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_index(op.f("ix_contacts_name"), "contacts", ["name"], unique=False)
    op.create_index(op.f("ix_contacts_phone"), "contacts", ["phone"], unique=True)
    op.create_index(op.f("ix_contacts_surname"), "contacts", ["surname"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contacts_surname"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_phone"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_name"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_birthday"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_additionally"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
